// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Delete(arg1:number):Promise<models.Product>;

export function List():Promise<Array<models.Product>>;

export function Store(arg1:models.Product):Promise<models.Product>;

export function Update(arg1:number,arg2:models.Product):Promise<models.Product>;
