// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Delete(arg1:number):Promise<models.Purchase>;

export function List():Promise<Array<models.Purchase>>;

export function Store(arg1:models.Purchase):Promise<models.Purchase>;

export function Update(arg1:number,arg2:models.Purchase):Promise<models.Purchase>;
