// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Delete(arg1:number):Promise<models.Supplier>;

export function List():Promise<Array<models.Supplier>>;

export function Store(arg1:models.Supplier):Promise<models.Supplier>;

export function Update(arg1:number,arg2:models.Supplier):Promise<models.Supplier>;
