// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['controllers']['SupplierController']['Delete'](arg1);
}

export function List() {
  return window['go']['controllers']['SupplierController']['List']();
}

export function Store(arg1) {
  return window['go']['controllers']['SupplierController']['Store'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['controllers']['SupplierController']['Update'](arg1, arg2);
}
